"""
Training data for crime type classification.
Maps FIR description text → crime type label.
Labels match the CRIME_TYPES used in the frontend.
"""

TRAINING_DATA = [
    # ── Theft ──
    ("Someone stole my bike near the railway station", "Theft"),
    ("My wallet was pickpocketed at the bus stop", "Theft"),
    ("Mobile phone stolen from my pocket in the market", "Theft"),
    ("Thief broke into my car and took my laptop", "Theft"),
    ("My bicycle was stolen from outside the school", "Theft"),
    ("Someone took my bag when I was not looking", "Theft"),
    ("A person snatched my gold chain while I was walking", "Theft"),
    ("My shop was broken into and all cash was stolen", "Theft"),
    ("Shoplifting incident at the grocery store", "Theft"),
    ("Missing valuables from my hotel room", "Theft"),
    ("Unknown person stole my vehicle from parking lot", "Theft"),
    ("My luggage was stolen from the train compartment", "Theft"),
    ("I found my house burgled when I came home and jewels missing", "Theft"),
    ("Cash taken from my desk drawer in the office", "Theft"),
    ("My scooter was stolen from outside the temple", "Theft"),
    ("Someone removed my parked motorcycle from outside my house", "Theft"),
    ("ATM card was stolen from my purse", "Theft"),
    ("Someone stole the spare tyre from my car", "Theft"),
    ("My neighbour stole my packages delivered to my doorstep", "Theft"),
    ("I was pickpocketed in a crowded area during the festival", "Theft"),

    # ── Assault ──
    ("I was attacked and beaten by a group of men", "Assault"),
    ("A person hit me with an iron rod", "Assault"),
    ("I was punched in the face during a fight", "Assault"),
    ("Physical assault by my neighbour over a land dispute", "Assault"),
    ("Someone threw acid on me near the college", "Assault"),
    ("I was beaten up by unknown persons at night", "Assault"),
    ("A drunk man attacked me with a bottle", "Assault"),
    ("Multiple people ganged up and beat me", "Assault"),
    ("I was slapped and pushed by a shop owner", "Assault"),
    ("Road rage incident where the other driver assaulted me", "Assault"),
    ("I was stabbed by an unknown attacker", "Assault"),
    ("A group of men attacked me with sticks and bats", "Assault"),
    ("Someone threw stones at me causing injuries", "Assault"),
    ("I was struck repeatedly after a verbal argument", "Assault"),
    ("Bodily harm caused by a stranger in the parking lot", "Assault"),
    ("Got beaten by two persons over a parking dispute", "Assault"),
    ("My colleague physically attacked me at the workplace", "Assault"),
    ("An individual hit me with a wooden plank", "Assault"),
    ("I suffered injuries after being kicked and punched", "Assault"),
    ("A violent altercation left me with broken bones", "Assault"),

    # ── Robbery ──
    ("Armed men robbed the bank this morning", "Robbery"),
    ("Robbers held me at gunpoint and took my money", "Robbery"),
    ("Jewellery store was robbed at gunpoint", "Robbery"),
    ("Two men on a bike snatched my purse at knifepoint", "Robbery"),
    ("A gang robbed the ATM at night", "Robbery"),
    ("Armed robbery at the petrol pump", "Robbery"),
    ("Men with weapons looted the cash register", "Robbery"),
    ("Robbery at my house, thieves had weapons", "Robbery"),
    ("I was robbed at knifepoint while walking home", "Robbery"),
    ("Dacoits robbed the bus passengers of their valuables", "Robbery"),
    ("A person with a gun took all my belongings", "Robbery"),
    ("Highway robbery while we were traveling at night", "Robbery"),
    ("Masked men looted the pawn shop using machetes", "Robbery"),
    ("Someone pointed a knife at me and demanded my phone", "Robbery"),
    ("Group of armed men stormed in and looted the store", "Robbery"),
    ("Hold up at the convenience store with a firearm", "Robbery"),
    ("I was mugged at gunpoint near the bridge", "Robbery"),
    ("Dacoity with firearms at the village money lender", "Robbery"),
    ("Gang of robbers looted all gold from the shop", "Robbery"),
    ("Cash van was robbed by armed criminals on the highway", "Robbery"),

    # ── Fraud ──
    ("Someone created a fake identity to take a loan in my name", "Fraud"),
    ("I was cheated in an online shopping transaction", "Fraud"),
    ("Fake insurance scheme took my money", "Fraud"),
    ("Ponzi scheme fraud took all my savings", "Fraud"),
    ("Cheque bounce and financial fraud by business partner", "Fraud"),
    ("Identity theft used for bank fraud", "Fraud"),
    ("Real estate fraud, fake property documents", "Fraud"),
    ("I was scammed by a fake job offer", "Fraud"),
    ("Credit card fraud, unauthorized transactions on my card", "Fraud"),
    ("Someone impersonated me and withdrew money from my account", "Fraud"),
    ("Investment scam promising high returns", "Fraud"),
    ("Fake lottery scheme collected money from me", "Fraud"),
    ("A company took advance payment but never delivered the product", "Fraud"),
    ("Fraudulent phone call tricked me into giving OTP", "Fraud"),
    ("Forged my signature on financial documents", "Fraud"),
    ("Insurance claim fraud by the garage mechanic", "Fraud"),
    ("My business partner embezzled company funds", "Fraud"),
    ("Online phishing attack stole my bank credentials", "Fraud"),
    ("E-commerce seller sent fake product after taking money", "Fraud"),
    ("Chit fund company ran away with all investor money", "Fraud"),

    # ── Cybercrime ──
    ("My social media account was hacked", "Cybercrime"),
    ("Someone hacked my bank account online", "Cybercrime"),
    ("Received threatening messages on social media", "Cybercrime"),
    ("My email was compromised and used for phishing", "Cybercrime"),
    ("Ransomware attack on my computer and they demand bitcoin", "Cybercrime"),
    ("Morphed photos of me were uploaded on the internet", "Cybercrime"),
    ("Data breach leaked my personal information online", "Cybercrime"),
    ("Someone created a fake social media profile using my photos", "Cybercrime"),
    ("I was blackmailed with my private photos online", "Cybercrime"),
    ("Online stalking and harassment through WhatsApp", "Cybercrime"),
    ("My website was defaced by hackers", "Cybercrime"),
    ("Unauthorized access to my email account", "Cybercrime"),
    ("DDoS attack brought down my online business", "Cybercrime"),
    ("Cryptocurrency mining malware installed on my systems", "Cybercrime"),
    ("Someone is spreading defamatory content about me on social media", "Cybercrime"),
    ("Online dating scam extorting money using personal chats", "Cybercrime"),
    ("My company server was hacked and data stolen", "Cybercrime"),
    ("Spam emails with malware attachments targeted my organization", "Cybercrime"),
    ("Someone is using my WiFi to do illegal activities", "Cybercrime"),
    ("Dark web listing of my stolen personal data", "Cybercrime"),

    # ── Harassment ──
    ("My boss has been making unwanted advances at work", "Harassment"),
    ("I am being stalked by an unknown person daily", "Harassment"),
    ("Continuous threatening phone calls from an unknown number", "Harassment"),
    ("Sexual harassment at the workplace", "Harassment"),
    ("A neighbour keeps making obscene remarks to my daughter", "Harassment"),
    ("Someone is following me everywhere", "Harassment"),
    ("Verbal abuse and threats from my landlord", "Harassment"),
    ("Getting bullied and intimidated at school", "Harassment"),
    ("Persistent unwanted contact despite warnings", "Harassment"),
    ("Stalking and watching my daily routine", "Harassment"),
    ("Threatening messages sent to my family members", "Harassment"),
    ("Eve teasing and catcalling on the way to college", "Harassment"),
    ("Someone keeps making vulgar calls to me at night", "Harassment"),
    ("Neighbour is intimidating and threatening us to vacate", "Harassment"),
    ("Group of men passing lewd comments every evening", "Harassment"),
    ("Workplace bullying by senior colleagues", "Harassment"),
    ("Being harassed by a money lender for repayment", "Harassment"),
    ("Ex-boyfriend continuously sending threatening texts", "Harassment"),
    ("Someone put up posters defaming my character", "Harassment"),
    ("Daily intimidation and verbal threats by local goon", "Harassment"),

    # ── Vandalism ──
    ("Someone broke the windows of my car", "Vandalism"),
    ("Graffiti sprayed on the walls of my house", "Vandalism"),
    ("My shop signboard was deliberately damaged", "Vandalism"),
    ("Someone slashed the tyres of my vehicle", "Vandalism"),
    ("Public property destroyed during protest", "Vandalism"),
    ("Deliberately damaged my boundary wall", "Vandalism"),
    ("Someone threw paint on my front door", "Vandalism"),
    ("My garden plants and decorations were destroyed", "Vandalism"),
    ("Car scratched intentionally in the parking area", "Vandalism"),
    ("Street lights in our colony were deliberately broken", "Vandalism"),
    ("Windows of the school were smashed at night", "Vandalism"),
    ("Someone keyed my car leaving deep scratches", "Vandalism"),
    ("CCTV cameras at our office were smashed", "Vandalism"),
    ("Park benches and dustbins destroyed by miscreants", "Vandalism"),
    ("The fence around our property was torn down", "Vandalism"),

    # ── Burglary ──
    ("Someone broke into my house while I was away on vacation", "Burglary"),
    ("Forced entry through my back door, electronics missing", "Burglary"),
    ("My apartment was broken into and ransacked", "Burglary"),
    ("Intruder entered through the window and stole cash from the safe", "Burglary"),
    ("Lock on the door was broken, all valuables are gone", "Burglary"),
    ("Burglary at night while the family was sleeping", "Burglary"),
    ("Store was broken into last night, inventory is missing", "Burglary"),
    ("Unknown persons entered my godown by cutting the lock", "Burglary"),
    ("House break-in and theft of gold ornaments", "Burglary"),
    ("My office was broken into over the weekend", "Burglary"),
    ("Garage was broken into and power tools were stolen", "Burglary"),
    ("Forced entry into warehouse and goods robbed", "Burglary"),
    ("My flat was burgled and laptop, TV and cash taken", "Burglary"),
    ("Someone got into my shop through the ceiling and stole goods", "Burglary"),
    ("Home invasion while we were out, jewelry taken from the safe", "Burglary"),

    # ── Kidnapping ──
    ("My child was taken away by unknown persons near the school", "Kidnapping"),
    ("A person was forcefully taken into a van", "Kidnapping"),
    ("My son has been abducted for ransom", "Kidnapping"),
    ("Kidnappers called demanding money for my relative", "Kidnapping"),
    ("Child went missing and was last seen with a stranger", "Kidnapping"),
    ("My daughter has been held captive by the accused", "Kidnapping"),
    ("Unauthorized custody of a minor child", "Kidnapping"),
    ("Three men forced my brother into a car and drove away", "Kidnapping"),
    ("Ransom call received after my businessman friend disappeared", "Kidnapping"),
    ("A woman was abducted from her workplace and held hostage", "Kidnapping"),
    ("Gang has kidnapped a local leader and demanding ransom", "Kidnapping"),
    ("My child did not return from school and we suspect abduction", "Kidnapping"),
    ("Someone forcibly took my wife from outside the house", "Kidnapping"),
    ("Two men dragged a boy into their vehicle near the park", "Kidnapping"),
    ("My employee was kidnapped on the way back from work", "Kidnapping"),

    # ── Drug Offense ──
    ("Drugs are being sold near the school campus", "Drug Offense"),
    ("Illegal drug manufacturing in the neighbourhood", "Drug Offense"),
    ("My neighbour is dealing drugs from his house", "Drug Offense"),
    ("Found suspicious drug packets near the park", "Drug Offense"),
    ("Drug peddlers are active in this area at night", "Drug Offense"),
    ("Marijuana cultivation discovered in the farmland", "Drug Offense"),
    ("Cannabis and other narcotics found in a vehicle", "Drug Offense"),
    ("Drug trafficking network operating in the locality", "Drug Offense"),
    ("Youth in the area are being supplied drugs illegally", "Drug Offense"),
    ("Smuggling of drugs across the border", "Drug Offense"),
    ("Cocaine packets seized from a suspect", "Drug Offense"),
    ("Drug lab found in an abandoned building", "Drug Offense"),
    ("Suspicious powder substance found in a parcel", "Drug Offense"),
    ("Illegal sale of prescription drugs without license", "Drug Offense"),
    ("Heroin dealing at the corner of the street", "Drug Offense"),

    # ── Extortion ──
    ("Local goons demanding protection money from shops", "Extortion"),
    ("Threatened to release private photos unless I pay money", "Extortion"),
    ("Receiving threats for not paying hafta to local gang", "Extortion"),
    ("Blackmail for money using personal information", "Extortion"),
    ("Demanding large sum or they will harm my family", "Extortion"),
    ("Protection racket operating in the market area", "Extortion"),
    ("Threatened to damage my shop if I dont pay up", "Extortion"),
    ("Monthly extortion demands from criminal gang", "Extortion"),
    ("Gang threatening business owners for regular payments", "Extortion"),
    ("I am being extorted by someone who has my personal videos", "Extortion"),
    ("Threatening to burn my crops unless I pay lakhs", "Extortion"),
    ("Demanding money regularly under threat of violence", "Extortion"),
    ("Blackmail using compromising information about my family", "Extortion"),
    ("A group is collecting forced donations from all shopkeepers", "Extortion"),
    ("Threatening letters demanding money sent to my home", "Extortion"),

    # ── Homicide ──
    ("A dead body was found near the river with stab wounds", "Homicide"),
    ("My relative was murdered last night", "Homicide"),
    ("Someone shot and killed a person in the neighbourhood", "Homicide"),
    ("Body found with signs of strangulation", "Homicide"),
    ("A man was beaten to death during a fight", "Homicide"),
    ("Suspicious death at the construction site", "Homicide"),
    ("My brother was killed in a gang fight", "Homicide"),
    ("Bullet wounds found on the victim's body", "Homicide"),
    ("Unidentified body discovered in the forest area", "Homicide"),
    ("Honour killing of a young woman by her family", "Homicide"),
    ("Man found dead with knife injuries in his apartment", "Homicide"),
    ("A person was poisoned to death by someone known", "Homicide"),
    ("Dead body found floating in the lake", "Homicide"),
    ("Murder committed during a domestic dispute", "Homicide"),
    ("Victim was killed execution-style with gunshot to head", "Homicide"),

    # ── Arson ──
    ("Someone set fire to my shop at night", "Arson"),
    ("Deliberate fire at the warehouse causing heavy losses", "Arson"),
    ("A mob set vehicles on fire during the riot", "Arson"),
    ("My house was intentionally set on fire", "Arson"),
    ("Forest fire started deliberately in the nearby hills", "Arson"),
    ("Someone threw petrol bomb at the building", "Arson"),
    ("Farm was set ablaze by miscreants", "Arson"),
    ("Factory fire was suspected to be arson", "Arson"),
    ("Fire started intentionally at the godown", "Arson"),
    ("Arson attack on the government office", "Arson"),
    ("Someone poured kerosene and set fire to the car", "Arson"),
    ("Barn was deliberately burned down along with cattle", "Arson"),
    ("Fire started in the shop after someone broke in at night", "Arson"),
    ("Suspected arson at the restaurant after a dispute", "Arson"),
    ("Molotov cocktails hurled at the building", "Arson"),

    # ── Trespassing ──
    ("Unknown person enters my property every night", "Trespassing"),
    ("Someone broke in and stayed in my vacant house without permission", "Trespassing"),
    ("Unauthorized entry on my agricultural land", "Trespassing"),
    ("A person was found hiding inside my compound wall", "Trespassing"),
    ("Strangers camping illegally on my property", "Trespassing"),
    ("Repeated unauthorized access to my private land", "Trespassing"),
    ("Someone climbed over the fence into my backyard", "Trespassing"),
    ("Encroachment on our community plot by a builder", "Trespassing"),
    ("Person refused to leave my property when asked", "Trespassing"),
    ("Illegal occupation of my vacant flat", "Trespassing"),
    ("Someone parks their vehicles on my private land daily", "Trespassing"),
    ("Intruder found on my rooftop at midnight", "Trespassing"),
    ("Squatters have taken over my empty house", "Trespassing"),
    ("Neighbour's construction is encroaching into my land", "Trespassing"),
    ("People are illegally entering the restricted area of the factory", "Trespassing"),

    # ── Forgery ──
    ("Someone forged my signature on property documents", "Forgery"),
    ("Fake degree certificates being used for a government job", "Forgery"),
    ("Falsified documents submitted for land registration", "Forgery"),
    ("Counterfeit vehicle registration documents found", "Forgery"),
    ("My signature was forged on a cheque", "Forgery"),
    ("Fake currency notes received from the ATM machine", "Forgery"),
    ("Forged will presented for inheritance claim", "Forgery"),
    ("Duplicate identity cards being manufactured", "Forgery"),
    ("Someone made a fake stamp paper for illegal transactions", "Forgery"),
    ("Fraudulent alteration of the sale deed", "Forgery"),
    ("Counterfeiting of government seals and stamps", "Forgery"),
    ("Fake medical certificates issued by unauthorized persons", "Forgery"),
    ("Bogus passport application with forged documents", "Forgery"),
    ("Tampered records submitted to the court", "Forgery"),
    ("Fake rental agreement presented as evidence", "Forgery"),

    # ── DUI ──
    ("A drunk driver crashed into my parked car", "DUI"),
    ("Person driving under the influence hit a pedestrian", "DUI"),
    ("Drunk driving caused an accident on the highway", "DUI"),
    ("Driver was visibly intoxicated and swerving on the road", "DUI"),
    ("Alcohol impaired driver ran a red signal", "DUI"),
    ("A drunk truck driver caused a pile up on the highway", "DUI"),
    ("Someone was driving under influence and caused property damage", "DUI"),
    ("Drunk driver hit my compound wall and drove off", "DUI"),
    ("Intoxicated person driving recklessly in residential area", "DUI"),
    ("A person was caught driving with blood alcohol above the limit", "DUI"),

    # ── Traffic Violation ──
    ("Vehicle ran the red light and caused accident", "Traffic Violation"),
    ("Reckless driving on the wrong side of the road", "Traffic Violation"),
    ("Hit and run accident, vehicle fled the scene", "Traffic Violation"),
    ("Overspeeding on the school zone road", "Traffic Violation"),
    ("Driver violated multiple traffic signals", "Traffic Violation"),
    ("Bike rider driving without helmet caused accident", "Traffic Violation"),
    ("Car drove on the footpath injuring pedestrians", "Traffic Violation"),
    ("Truck overloaded beyond capacity on the highway", "Traffic Violation"),
    ("Driving without a valid license on main road", "Traffic Violation"),
    ("Signal jumping caused a collision at the intersection", "Traffic Violation"),

    # ── Sexual Offense ──
    ("Molestation incident reported at the bus stop", "Sexual Offense"),
    ("A woman was assaulted in the office", "Sexual Offense"),
    ("Inappropriate touching in a crowded train", "Sexual Offense"),
    ("A minor was sexually abused by a relative", "Sexual Offense"),
    ("Rape reported inside the university campus", "Sexual Offense"),
    ("Sexual assault on a woman returning from work at night", "Sexual Offense"),
    ("A girl was molested outside her hostel", "Sexual Offense"),
    ("Child sexual abuse by the school teacher", "Sexual Offense"),
    ("Voyeurism incident in the women's changing room", "Sexual Offense"),
    ("Indecent exposure reported near the children's park", "Sexual Offense"),

    # ── Racketeering ──
    ("Illegal gambling den operating in the basement", "Racketeering"),
    ("Large scale organized smuggling ring busted", "Racketeering"),
    ("Syndicate involved in money laundering and illegal trade", "Racketeering"),
    ("Organized crime group running illegal betting activities", "Racketeering"),
    ("Mafia running a network of illegal businesses in the city", "Racketeering"),
    ("Systematic corruption and bribery by a crime syndicate", "Racketeering"),
    ("Organized crime operation controlling the illegal liquor trade", "Racketeering"),
    ("Gang operating a loan sharking racket in the market area", "Racketeering"),
    ("Crime syndicate involved in human trafficking", "Racketeering"),
    ("Network of illegal arms dealing across state borders", "Racketeering"),

    # ── Counterfeiting ──
    ("Fake currency notes circulating in the local market", "Counterfeiting"),
    ("Counterfeit products being sold as branded goods", "Counterfeiting"),
    ("Duplicate medicines manufactured and distributed illegally", "Counterfeiting"),
    ("Fake government stamps and seals being used for documents", "Counterfeiting"),
    ("Counterfeit notes found at the bank deposit", "Counterfeiting"),
    ("Large quantity of fake money recovered from a printing press", "Counterfeiting"),
    ("Counterfeit branded electronics being sold online", "Counterfeiting"),
    ("Fake currency notes received in a cash transaction", "Counterfeiting"),
    ("Counterfeit labels on food products in the store", "Counterfeiting"),
    ("Illegal printing of fake five hundred rupee notes", "Counterfeiting"),
]
