import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Container, Button, Card, Alert, Table, Row, Col, Spinner } from 'react-bootstrap';
import Sidebar from '../components/Sidebar';
import Footer from '../components/Footer';
import { advancedAPI } from '../api/client';
import '../styles/dashboard.css';

const EXPORT_TYPES = [
  { value: 'firs', label: 'FIR Records', icon: 'fas fa-file-alt', color: '#0ea5e9', desc: 'All FIR records with crime details, status, and workflow stage' },
  { value: 'criminals', label: 'Criminal Records', icon: 'fas fa-user-secret', color: '#ef4444', desc: 'Criminal database with crime types, stations, and status' },
  { value: 'summary', label: 'Crime Summary', icon: 'fas fa-chart-pie', color: '#10b981', desc: 'Aggregate crime statistics by type with status breakdown' },
];

const ExportReports = () => {
  const navigate = useNavigate();
  const role = localStorage.getItem('userRole');
  const [selectedType, setSelectedType] = useState('firs');
  const [exporting, setExporting] = useState('');
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [previewData, setPreviewData] = useState(null);
  const [previewHeaders, setPreviewHeaders] = useState([]);
  const [previewLoading, setPreviewLoading] = useState(false);

  if (role !== 'Admin') {
    navigate('/login');
    return null;
  }

  const handlePreview = async (format) => {
    setError('');
    if (format === 'csv') {
      await handleCSVExport();
      return;
    }
    
    setPreviewLoading(true);
    try {
      const res = await advancedAPI.exportJSON(selectedType);
      const data = res.data?.data || [];
      if (data.length === 0) { 
        setError('No data to export'); 
        return; 
      }
      const headers = Object.keys(data[0]);
      setPreviewHeaders(headers);
      setPreviewData({ data, format });
    } catch (err) {
      setError('Failed to load data');
    } finally {
      setPreviewLoading(false);
    }
  };

  const handleCSVExport = async () => {
    setExporting('csv');
    setError('');
    try {
      const res = await advancedAPI.exportCSV(selectedType);
      const blob = new Blob([res.data], { type: 'text/csv' });
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `${selectedType}_report_${Date.now()}.csv`;
      link.click();
      window.URL.revokeObjectURL(url);
      setSuccess('CSV downloaded successfully!');
    } catch (err) {
      setError('CSV export failed');
    } finally {
      setExporting('');
      setPreviewLoading(false);
      setTimeout(() => setSuccess(''), 3000);
    }
  };

  const handleDownloadExcel = () => {
    if (!previewData?.data) return;
    const data = previewData.data;
    const headers = Object.keys(data[0]);
    const rows = [headers.join('\t'), ...data.map(row => headers.map(h => String(row[h] ?? '').replace(/\t/g, ' ')).join('\t'))];
    const blob = new Blob([rows.join('\n')], { type: 'text/tab-separated-values' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${selectedType}_report_${Date.now()}.xls`;
    link.click();
    window.URL.revokeObjectURL(url);
    setSuccess('✓ Excel file downloaded successfully!');
    setTimeout(() => setSuccess(''), 4000);
  };

  const handlePrintPDF = () => {
    if (!previewData?.data) return;
    const data = previewData.data;
    const headers = Object.keys(data[0]);
    let html = `
      <!DOCTYPE html><html><head><title>Crime Report - ${selectedType}</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 20px; }
        h1 { color: #1e293b; border-bottom: 2px solid #0ea5e9; padding-bottom: 10px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 11px; }
        th { background: #0ea5e9; color: white; padding: 8px 6px; text-align: left; }
        td { padding: 6px; border-bottom: 1px solid #e5e7eb; }
        tr:nth-child(even) { background: #f8fafc; }
        .footer { margin-top: 30px; color: #94a3b8; font-size: 11px; text-align: center; }
      </style></head><body>
      <h1>Crime Management System — ${selectedType.charAt(0).toUpperCase() + selectedType.slice(1)} Report</h1>
      <p>Generated on ${new Date().toLocaleString()} | Total Records: ${data.length}</p>
      <table><thead><tr>${headers.map(h => `<th>${h}</th>`).join('')}</tr></thead><tbody>`;
    data.forEach(row => {
      html += '<tr>' + headers.map(h => `<td>${row[h] ?? ''}</td>`).join('') + '</tr>';
    });
    html += `</tbody></table><div class="footer">Generated by Crime Management System</div></body></html>`;
    
    const printWindow = window.open('', '_blank');
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => { 
      printWindow.print();
      // Don't close the window, let user handle it after printing
    }, 500);
    
    setSuccess('✓ PDF print dialog opened! Select "Save as PDF" to download.');
    setTimeout(() => setSuccess(''), 5000);
  };

  // If preview data is available, show the preview page
  if (previewData) {
    return (
      <div style={{ display: 'flex', minHeight: '100vh', paddingTop: '38px', backgroundColor: '#ffffff' }}>
        <div style={{ position: 'fixed', left: 0, top: 0, height: '100vh', zIndex: 1000 }}>
          <Sidebar />
        </div>
        <div style={{ flex: 1, marginLeft: '250px', overflowX: 'hidden', overflowY: 'auto' }}>
          <Container fluid className="py-4 px-4 page-stagger">
            {/* Header Section */}
            <div className="d-flex align-items-center justify-content-between mb-4" style={{ animation: 'fadeInDown 0.3s ease' }}>
              <div className="d-flex align-items-center gap-3">
                <Button variant="outline-secondary" size="sm" style={{ borderRadius: 8, fontWeight: 600, padding: '8px 16px' }}
                  onClick={() => setPreviewData(null)}>
                  <i className="fas fa-arrow-left me-2"></i> Back to Export
                </Button>
                <div>
                  <h4 className="fw-bold mb-0">
                    <i className={`${EXPORT_TYPES.find(t => t.value === selectedType)?.icon} me-2`} style={{ color: EXPORT_TYPES.find(t => t.value === selectedType)?.color }}></i>
                    {EXPORT_TYPES.find(t => t.value === selectedType)?.label} Preview
                  </h4>
                  <small className="text-muted">{previewData.data.length} records found</small>
                </div>
              </div>
            </div>

            {/* Download Buttons Section */}
            <Card className="border-0 shadow-sm mb-4" style={{ borderRadius: 12, backgroundColor: '#f0f9ff', borderLeft: '4px solid #0ea5e9' }}>
              <Card.Body className="p-3">
                <div className="d-flex align-items-center justify-content-between">
                  <div>
                    <h6 className="fw-bold mb-1"><i className="fas fa-download me-2" style={{ color: '#0ea5e9' }}></i>Download Options</h6>
                    <small className="text-muted">Select a format to download this report</small>
                  </div>
                  <div className="d-flex gap-2">
                    {previewData.format === 'excel' && (
                      <Button variant="primary" size="sm" style={{ borderRadius: 8, fontWeight: 600, padding: '10px 20px' }} onClick={handleDownloadExcel}>
                        <i className="fas fa-download me-1"></i> Download Excel
                      </Button>
                    )}
                    {previewData.format === 'pdf' && (
                      <Button variant="danger" size="sm" style={{ borderRadius: 8, fontWeight: 600, padding: '10px 20px' }} onClick={handlePrintPDF}>
                        <i className="fas fa-file-pdf me-1"></i> Print as PDF
                      </Button>
                    )}
                  </div>
                </div>
              </Card.Body>
            </Card>

            {success && <Alert variant="success" dismissible onClose={() => setSuccess('')}><i className="fas fa-check-circle me-2"></i>{success}</Alert>}

            {/* Preview Table */}
            <Card className="border-0 shadow-sm" style={{ animation: 'fadeInUp 0.4s ease', borderRadius: 12, overflow: 'hidden' }}>
              <Card.Body style={{ padding: 0, maxHeight: 'calc(100vh - 350px)', overflowY: 'auto' }}>
                <Table hover responsive style={{ marginBottom: 0, fontSize: '0.82rem' }}>
                  <thead style={{ position: 'sticky', top: 0, background: '#f8fafc', zIndex: 10 }}>
                    <tr>
                      <th style={{ padding: '10px 12px', fontWeight: 700, fontSize: '0.75rem', textTransform: 'uppercase', color: '#0f172a' }}>Sr. No.</th>
                      {previewHeaders.map(h => (
                        <th key={h} style={{ padding: '10px 12px', fontWeight: 700, fontSize: '0.75rem', textTransform: 'uppercase', color: '#0f172a', whiteSpace: 'nowrap' }}>{h}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {previewData.data.map((row, idx) => (
                      <tr key={idx}>
                        <td style={{ padding: '8px 12px', fontWeight: 600 }}>{idx + 1}</td>
                        {previewHeaders.map(h => (
                          <td key={h} style={{ padding: '8px 12px', maxWidth: 200, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{row[h] ?? '-'}</td>
                        ))}
                      </tr>
                    ))}
                  </tbody>
                </Table>
              </Card.Body>
            </Card>
          </Container>
          <Footer />
        </div>
      </div>
    );
  }

  return (
    <div style={{ display: 'flex', minHeight: '100vh', paddingTop: '38px', backgroundColor: '#f9fafb' }}>
      <div style={{ position: 'fixed', left: 0, top: 0, height: '100vh', zIndex: 1000 }}>
        <Sidebar />
      </div>
      <div style={{ flex: 1, marginLeft: '250px', overflowX: 'hidden', overflowY: 'auto' }}>
        <Container fluid style={{ paddingTop: '20px', paddingBottom: '40px', minHeight: '100%' }} className="px-4 page-stagger">
          <div className="d-flex align-items-center gap-3 mb-4" style={{ animation: 'fadeInDown 0.3s ease' }}>
            <Button variant="outline-secondary" size="sm" style={{ borderRadius: 8, fontWeight: 600, padding: '8px 16px' }}
              onClick={() => navigate(-1)}>
              <i className="fas fa-arrow-left me-2"></i> Back
            </Button>
            <div>
              <h3 className="fw-bold mb-0"><i className="fas fa-download me-2" style={{ color: '#10b981' }}></i>Export Reports</h3>
              <p className="text-muted mb-0" style={{ fontSize: '0.85rem' }}>Download crime statistics in CSV, Excel, or PDF formats</p>
            </div>
          </div>

          {error && <Alert variant="danger" dismissible onClose={() => setError('')}>{error}</Alert>}
          {success && <Alert variant="success" dismissible onClose={() => setSuccess('')}><i className="fas fa-check-circle me-2"></i>{success}</Alert>}

          {/* Data Type Selection */}
          <Row className="g-3 mb-4">
            {EXPORT_TYPES.map((t, i) => (
              <Col md={4} key={t.value}>
                <Card
                  className="border-0 shadow-sm h-100"
                  style={{
                    cursor: 'pointer',
                    border: selectedType === t.value ? `2px solid ${t.color}` : '2px solid transparent',
                    background: selectedType === t.value ? t.color + '08' : '#fff',
                    transition: 'all 0.3s ease',
                    transform: selectedType === t.value ? 'translateY(-4px)' : 'translateY(0)',
                    borderRadius: 14,
                    animation: `fadeInUp ${0.3 + i * 0.1}s ease`
                  }}
                  onClick={() => setSelectedType(t.value)}
                >
                  <Card.Body className="text-center py-4">
                    <div style={{
                      width: 60, height: 60, borderRadius: '50%',
                      background: t.color + '15', display: 'flex', alignItems: 'center', justifyContent: 'center',
                      margin: '0 auto 12px', transition: 'transform 0.3s',
                      transform: selectedType === t.value ? 'scale(1.1)' : 'scale(1)'
                    }}>
                      <i className={t.icon} style={{ fontSize: '1.5rem', color: t.color }}></i>
                    </div>
                    <h6 className="fw-bold">{t.label}</h6>
                    <p className="text-muted mb-0" style={{ fontSize: '0.8rem' }}>{t.desc}</p>
                    {selectedType === t.value && (
                      <div className="mt-2"><i className="fas fa-check-circle" style={{ color: t.color, fontSize: '1.1rem' }}></i></div>
                    )}
                  </Card.Body>
                </Card>
              </Col>
            ))}
          </Row>

          {/* Export Buttons - IMPORTANT: Always visible */}
          <Card className="border-0 shadow-sm" style={{ borderRadius: 14, animation: 'fadeInUp 0.5s ease', marginBottom: '30px' }}>
            <Card.Body className="p-4">
              <h6 className="fw-bold mb-3">
                <i className="fas fa-file-export me-2" style={{ color: '#6366f1' }}></i>
                Export {EXPORT_TYPES.find(t => t.value === selectedType)?.label || 'Data'}
              </h6>
              <Row className="g-3">
                <Col md={4} xs={12}>
                  <Button
                    variant="success"
                    className="w-100 py-3 d-flex align-items-center justify-content-center gap-2"
                    onClick={() => handlePreview('csv')}
                    disabled={exporting === 'csv' || previewLoading}
                    style={{ borderRadius: 12, fontSize: '1rem', transition: 'transform 0.2s', fontWeight: 600, minHeight: '60px' }}
                    onMouseEnter={e => e.currentTarget.style.transform = 'translateY(-2px)'}
                    onMouseLeave={e => e.currentTarget.style.transform = 'translateY(0)'}
                  >
                    {exporting === 'csv' ? <Spinner size="sm" /> : <i className="fas fa-file-csv" style={{ fontSize: '1.3rem' }}></i>}
                    Download CSV
                  </Button>
                </Col>
                <Col md={4} xs={12}>
                  <Button
                    variant="primary"
                    className="w-100 py-3 d-flex align-items-center justify-content-center gap-2"
                    onClick={() => handlePreview('excel')}
                    disabled={previewLoading}
                    style={{ borderRadius: 12, fontSize: '1rem', transition: 'transform 0.2s', fontWeight: 600, minHeight: '60px' }}
                    onMouseEnter={e => e.currentTarget.style.transform = 'translateY(-2px)'}
                    onMouseLeave={e => e.currentTarget.style.transform = 'translateY(0)'}
                  >
                    {previewLoading ? <Spinner size="sm" /> : <i className="fas fa-file-excel" style={{ fontSize: '1.3rem' }}></i>}
                    Preview & Export Excel
                  </Button>
                </Col>
                <Col md={4} xs={12}>
                  <Button
                    variant="danger"
                    className="w-100 py-3 d-flex align-items-center justify-content-center gap-2"
                    onClick={() => handlePreview('pdf')}
                    disabled={previewLoading}
                    style={{ borderRadius: 12, fontSize: '1rem', transition: 'transform 0.2s', fontWeight: 600, minHeight: '60px' }}
                    onMouseEnter={e => e.currentTarget.style.transform = 'translateY(-2px)'}
                    onMouseLeave={e => e.currentTarget.style.transform = 'translateY(0)'}
                  >
                    {previewLoading ? <Spinner size="sm" /> : <i className="fas fa-file-pdf" style={{ fontSize: '1.3rem' }}></i>}
                    Preview & Export PDF
                  </Button>
                </Col>
              </Row>
            </Card.Body>
          </Card>
        </Container>
        <Footer />
      </div>
    </div>
  );
};

export default ExportReports;
