import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Container, Button, Card, Alert, Row, Col, Spinner } from 'react-bootstrap';
import Sidebar from '../components/Sidebar';
import { advancedAPI } from '../api/client';
import '../styles/dashboard.css';

const EXPORT_TYPES = [
  { value: 'firs', label: 'FIR Records', icon: 'fas fa-file-alt', color: '#0ea5e9', desc: 'All FIR records with crime details, status, and workflow stage' },
  { value: 'criminals', label: 'Criminal Records', icon: 'fas fa-user-secret', color: '#ef4444', desc: 'Criminal database with crime types, stations, and status' },
  { value: 'summary', label: 'Crime Summary', icon: 'fas fa-chart-pie', color: '#10b981', desc: 'Aggregate crime statistics by type with status breakdown' },
];

const ExportReports = () => {
  const navigate = useNavigate();
  const role = localStorage.getItem('userRole');
  const [exporting, setExporting] = useState('');
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');

  if (role !== 'Admin') {
    navigate('/login');
    return null;
  }

  const handleDownloadPDF = async (exportType) => {
    setError('');
    if (exporting) return;
    
    setExporting(exportType);
    try {
      const res = await advancedAPI.exportJSON(exportType);
      const data = res.data?.data || [];
      if (data.length === 0) { 
        setError('No data to export');
        setExporting('');
        return; 
      }
      
      // Generate PDF
      const headers = Object.keys(data[0]);
      let html = `
        <!DOCTYPE html><html><head><title>Crime Report - ${exportType}</title>
        <style>
          body { font-family: Arial, sans-serif; padding: 20px; }
          h1 { color: #1e293b; border-bottom: 2px solid #0ea5e9; padding-bottom: 10px; }
          table { width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 11px; }
          th { background: #0ea5e9; color: white; padding: 8px 6px; text-align: left; }
          td { padding: 6px; border-bottom: 1px solid #e5e7eb; }
          tr:nth-child(even) { background: #f8fafc; }
          .footer { margin-top: 30px; color: #94a3b8; font-size: 11px; text-align: center; }
        </style></head><body>
        <h1>Crime Management System — ${exportType.charAt(0).toUpperCase() + exportType.slice(1)} Report</h1>
        <p>Generated on ${new Date().toLocaleString()} | Total Records: ${data.length}</p>
        <table><thead><tr>${headers.map(h => `<th>${h}</th>`).join('')}</tr></thead><tbody>`;
      
      data.forEach(row => {
        html += '<tr>' + headers.map(h => `<td>${row[h] ?? ''}</td>`).join('') + '</tr>';
      });
      html += `</tbody></table><div class="footer">Generated by Crime Management System</div></body></html>`;
      
      const printWindow = window.open('', '_blank');
      printWindow.document.write(html);
      printWindow.document.close();
      printWindow.focus();
      setTimeout(() => { 
        printWindow.print();
        setSuccess('✓ PDF download initiated!');
        setTimeout(() => setSuccess(''), 3000);
      }, 500);
    } catch (err) {
      console.error('Export error:', err);
      setError('Failed to load data');
    } finally {
      setExporting('');
    }
  };





  return (
    <>
      <Sidebar />
      <div className="with-sidebar">
        <Container fluid className="mgmt-container" style={{ background: '#ffffff', paddingTop: '20px' }}>
          {/* Header - Title and Back Button */}
          <div className="d-flex justify-content-between align-items-center mb-4 gap-2" style={{ animation: 'fadeIn 0.35s cubic-bezier(.4,0,.2,1) both' }}>
            <div>
              <h2 className="fw-bold mb-0" style={{ color: '#1a1a1a', fontSize: '1.3rem' }}>
                <i className="fas fa-download me-2" style={{ color: '#10b981' }}></i>Export Reports
              </h2>
            </div>
            <Button 
              variant="outline-secondary" 
              size="sm" 
              onClick={() => navigate(-1)} 
              className="fw-bold"
              style={{ padding: '5px 14px', fontSize: '0.8rem', borderRadius: '8px' }}>
              <i className="fas fa-arrow-left me-1"></i>Back
            </Button>
          </div>

          {error && <Alert variant="danger" dismissible onClose={() => setError('')} style={{ animation: 'fadeInDown 0.3s ease' }}><i className="fas fa-exclamation-circle me-2"></i>{error}</Alert>}
          {success && <Alert variant="success" dismissible onClose={() => setSuccess('')} style={{ animation: 'fadeInDown 0.3s ease' }}><i className="fas fa-check-circle me-2"></i>{success}</Alert>}

          {/* Export Cards - 3 cards side by side */}
          <Row className="g-3">
            {EXPORT_TYPES.map((t, i) => (
              <Col lg={4} md={6} xs={12} key={t.value} style={{ animation: `fadeInUp ${0.3 + i * 0.1}s ease` }}>
                <Card
                  className="border-0 shadow-sm h-100"
                  style={{
                    borderRadius: 12,
                    background: '#ffffff',
                    borderLeft: `4px solid ${t.color}`,
                    transition: 'all 0.3s ease',
                    boxShadow: '0 2px 12px rgba(0,0,0,0.08)'
                  }}
                  onMouseEnter={e => {
                    e.currentTarget.style.transform = 'translateY(-4px)';
                    e.currentTarget.style.boxShadow = `0 8px 24px ${t.color}20`;
                  }}
                  onMouseLeave={e => {
                    e.currentTarget.style.transform = 'translateY(0)';
                    e.currentTarget.style.boxShadow = '0 2px 12px rgba(0,0,0,0.08)';
                  }}
                >
                  <Card.Body className="p-4 d-flex flex-column">
                    {/* Icon */}
                    <div style={{
                      width: 50, height: 50, borderRadius: '50%',
                      background: t.color + '15', display: 'flex', alignItems: 'center', justifyContent: 'center',
                      marginBottom: '12px'
                    }}>
                      <i className={t.icon} style={{ fontSize: '1.3rem', color: t.color }}></i>
                    </div>
                    
                    {/* Title and Description */}
                    <h6 className="fw-bold mb-1" style={{ fontSize: '1rem', color: '#1e293b' }}>{t.label}</h6>
                    <p className="text-muted mb-3" style={{ fontSize: '0.8rem', flex: 1 }}>{t.desc}</p>
                    
                    {/* Download Button */}
                    <Button
                      className="w-100 py-2 d-flex align-items-center justify-content-center gap-2"
                      onClick={() => handleDownloadPDF(t.value)}
                      disabled={exporting === t.value}
                      style={{ 
                        borderRadius: 8, 
                        fontSize: '0.85rem', 
                        transition: 'all 0.2s ease', 
                        fontWeight: 600,
                        background: t.color,
                        border: 'none',
                        color: '#fff',
                        marginTop: 'auto',
                        cursor: exporting === t.value ? 'not-allowed' : 'pointer'
                      }}
                      onMouseEnter={e => !e.currentTarget.disabled && (e.currentTarget.style.transform = 'translateY(-2px)')}
                      onMouseLeave={e => e.currentTarget.style.transform = 'translateY(0)'}
                    >
                      {exporting === t.value ? (
                        <><Spinner size="sm" /> Downloading...</>
                      ) : (
                        <><i className="fas fa-download"></i> Download</>
                      )}
                    </Button>
                  </Card.Body>
                </Card>
              </Col>
            ))}
          </Row>
        </Container>
      </div>
    </>
  );
};

export default ExportReports;
